use std::path::Path;
#[cfg(not(any(windows, target_os = "macos")))]
use std::process::Command;

use crate::error::{AppError, Result};
use crate::tls::install::command;

/// Firefox ignores `--proxy-server`, so the proxy is configured through a
/// dedicated profile instead of touching the user's own settings.
pub fn prepare_profile(profile: &Path, proxy_host: &str, proxy_port: u16) -> Result<()> {
    std::fs::create_dir_all(profile)?;
    std::fs::write(profile.join("user.js"), user_js(proxy_host, proxy_port))?;
    Ok(())
}

fn user_js(host: &str, port: u16) -> String {
    let mut prefs = vec![
        pref_int("network.proxy.type", 1),
        pref_str("network.proxy.http", host),
        pref_int("network.proxy.http_port", port as i64),
        pref_str("network.proxy.ssl", host),
        pref_int("network.proxy.ssl_port", port as i64),
        pref_bool("network.proxy.share_proxy_settings", true),
        pref_str("network.proxy.no_proxies_on", ""),
        pref_bool("network.proxy.allow_hijacking_localhost", true),
        pref_bool("network.dns.disablePrefetch", true),
        pref_bool("network.prefetch-next", false),
        pref_bool("browser.shell.checkDefaultBrowser", false),
        pref_bool("browser.aboutwelcome.enabled", false),
        pref_int("browser.startup.page", 0),
        pref_bool("datareporting.policy.dataSubmissionEnabled", false),
        pref_bool("datareporting.healthreport.uploadEnabled", false),
        pref_bool("toolkit.telemetry.enabled", false),
        pref_bool("app.shield.optoutstudies.enabled", false),
        pref_bool("trailhead.firstrun.didSeeAboutWelcome", true),
    ];

    // Windows and macOS Firefox can read the operating system trust store,
    // which is where Install CA puts the Vanguard authority.
    if cfg!(any(windows, target_os = "macos")) {
        prefs.push(pref_bool("security.enterprise_roots.enabled", true));
    }

    format!(
        "// Generated by Vanguard. This profile is isolated from your normal Firefox.\n{}\n",
        prefs.join("\n")
    )
}

fn pref_bool(key: &str, value: bool) -> String {
    format!("user_pref(\"{key}\", {value});")
}

fn pref_int(key: &str, value: i64) -> String {
    format!("user_pref(\"{key}\", {value});")
}

fn pref_str(key: &str, value: &str) -> String {
    format!("user_pref(\"{key}\", \"{value}\");")
}

/// On Linux the system trust store is not enough: Firefox keeps its own NSS
/// database per profile. Import the CA there when nss certutil is available.
#[cfg(not(any(windows, target_os = "macos")))]
pub fn trust_ca(profile: &Path, ca_cert: &Path) -> Result<bool> {
    if !ca_cert.exists() {
        return Ok(false);
    }
    if !nss_certutil_available() {
        return Ok(false);
    }

    let db = format!("sql:{}", profile.to_string_lossy());
    let _ = Command::new("certutil").args(["-N", "--empty-password", "-d", &db]).output();

    let status = Command::new("certutil")
        .args([
            "-A",
            "-n",
            "Vanguard Local CA",
            "-t",
            "C,,",
            "-i",
            &ca_cert.to_string_lossy(),
            "-d",
            &db,
        ])
        .status()
        .map_err(|e| AppError::Certificate(format!("could not run certutil: {e}")))?;

    Ok(status.success())
}

#[cfg(any(windows, target_os = "macos"))]
pub fn trust_ca(_profile: &Path, _ca_cert: &Path) -> Result<bool> {
    // Handled by security.enterprise_roots.enabled reading the OS trust store.
    Ok(true)
}

#[cfg(not(any(windows, target_os = "macos")))]
fn nss_certutil_available() -> bool {
    Command::new("sh")
        .args(["-c", "command -v certutil >/dev/null && certutil -H 2>&1 | grep -qi 'nss\\|database'"])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_points_firefox_at_the_proxy() {
        let js = user_js("127.0.0.1", 8080);
        assert!(js.contains("user_pref(\"network.proxy.type\", 1);"));
        assert!(js.contains("user_pref(\"network.proxy.http\", \"127.0.0.1\");"));
        assert!(js.contains("user_pref(\"network.proxy.http_port\", 8080);"));
        assert!(js.contains("user_pref(\"network.proxy.ssl_port\", 8080);"));
        assert!(
            js.contains("user_pref(\"network.proxy.allow_hijacking_localhost\", true);"),
            "localhost must not bypass the proxy"
        );
        assert!(!js.contains("user_pref(\"toolkit.telemetry.enabled\", true);"));
    }

    #[test]
    fn windows_and_macos_read_the_system_trust_store() {
        let js = user_js("127.0.0.1", 1);
        let expected = cfg!(any(windows, target_os = "macos"));
        assert_eq!(js.contains("security.enterprise_roots.enabled"), expected);
    }
}

pub fn spawn(exe: &str, profile: &Path, url: &str) -> Result<()> {
    let mut cmd = command(exe);
    cmd.arg("-no-remote");
    cmd.arg("-profile");
    cmd.arg(profile);
    if !url.is_empty() {
        cmd.arg("-new-tab");
        cmd.arg(url);
    }
    cmd.spawn()
        .map_err(|e| AppError::Proxy(format!("could not start Firefox: {e}")))?;
    Ok(())
}
